Repository kookmin-sw/capstone-2023-08, pull requests merged in 2023-03, with the labels that each got.

#26 frontend infolist add
  client/asset/clothes/product-image.jpg
  client/asset/image1.jpg
  client/asset/image2.png
  client/asset/image3.png
  client/asset/product-image.jpg
  client/assets/clothes/product-image.jpg
  client/assets/image1.jpg
  client/assets/image2.png
  client/assets/image3.png
  client/assets/product-image.jpg
  client/ios/Flutter/Debug.xcconfig
  client/ios/Flutter/Release.xcconfig
  client/ios/Podfile
  client/lib/main.dart
  client/lib/screen/clotheslist_screen.dart
  client/lib/screen/home_screen.dart
  client/lib/screen/login_screen.dart
  client/lib/screen/shoppingmall_screen.dart
  client/macos/Flutter/Flutter-Debug.xcconfig
  client/macos/Flutter/Flutter-Release.xcconfig
  client/macos/Podfile
  client/pubspec.lock
  client/pubspec.yaml
Labels: Front-end

#21 크롤링 모듈 개발
  crawler/musinsa-crawler.py
Labels: Back-end

#32 Git page 빌드오류해결
  .gitignore
  Gemfile
  Gemfile.lock
  _posts/2016-07-20-the-process-for-direct-sales.md
  _posts/2016-07-28-effective-upselling-techniques.md
  _posts/2016-08-02-sales-effectiveness.md
  _posts/2016-08-06-definition-of-sales.md
  _posts/2016-08-12-the-history-of-marketing.md
  index.html
Labels: documentation

#33 Git page indent 오류 해결
  _config.yml
Labels: documentation

#34 회원가입 및 로그인 기능 구현 완료
  .gitignore
  server/accounts/__init__.py
  server/accounts/admin.py
  server/accounts/apps.py
  server/accounts/migrations/0001_initial.py
  server/accounts/migrations/__init__.py
  server/accounts/models.py
  server/accounts/tests.py
  server/accounts/urls.py
  server/accounts/views.py
  server/virtual_fitting_app/settings.py
  server/virtual_fitting_app/urls.py
Labels: Back-end

#41 [Frontend] 메인 레이아웃 구성 - 하단바 분리 및 Named Routing
  client/lib/constant/page_name.dart
  client/lib/layout/bottom_navigator.dart
  client/lib/layout/main_layout.dart
  client/lib/layout/tab_item.dart
  client/lib/layout/tab_navigator.dart
  client/lib/main.dart
  client/lib/screen/camera_result.dart
  client/lib/screen/camera_screen.dart
  client/lib/screen/clotheslist_screen.dart
  client/lib/screen/home_screen.dart
  client/lib/screen/login_screen.dart
  client/lib/screen/my_page_screen.dart
  client/lib/screen/signup_success.dart
  crawler/musinsa-crawler.py
Labels: Front-end

#42 [Frontend] 카메라로 촬영하는 화면 개발
  client/lib/screen/camera_result.dart
  client/lib/screen/camera_screen.dart
  client/lib/screen/signup_success.dart
Labels: Front-end

#44 회원 가입 페이지 개발
  client/lib/screen/signup_screen.dart
Labels: Front-end

#52 Mysql DB 연동완료
  server/virtual_fitting_app/settings.py
Labels: Back-end

#60 modify setting for ec2
  server/virtual_fitting_app/settings.py
Labels: Back-end
