Repository kookmin-sw/capstone-2023-08, pull requests merged in 2023-05, with the labels that each got.

#106 modify to get bucket, file name from client
  server/s3_access/views.py
Labels: Back-end

#112 회원가입시 id 중복체크 분리 및 에러 핸들링 추가
  server/accounts/views.py
  server/virtual_fitting_app/urls.py
Labels: Back-end

#114 Permission setting
  server/accounts/views.py
  server/musinsa_list/urls.py
  server/musinsa_list/views.py
Labels: Back-end

#103 [FE] 회원가입~카메라 화면 변경
  client/.metadata
  client/asset/img/person_outline.jpg
  client/asset/img/splash_image.png
  client/asset/img/splash_image1.png
  client/asset/img/user.png
  client/lib/component/custom_text_form_field.dart
  client/lib/component/default_dialog.dart
  client/lib/component/one_button_dialog.dart
  client/lib/constant/colors.dart
  client/lib/constant/page_name.dart
  client/lib/constant/page_url.dart
  client/lib/data/account_model.dart
  client/lib/data/account_model.g.dart
  client/lib/data/camera_state.dart
  client/lib/dio/dio.dart
  client/lib/layout/default_layout.dart
  client/lib/layout/root_tab.dart
  client/lib/main.dart
  client/lib/screen/camera_result.dart
  client/lib/screen/camera_screen.dart
  client/lib/screen/fail_screen.dart
  client/lib/screen/find_account_screen.dart
  client/lib/screen/login_screen.dart
  client/lib/screen/result_screen.dart
  client/lib/screen/signup_result_screen.dart
  client/lib/screen/signup_screen.dart
  client/lib/screen/signup_success.dart
  client/lib/screen/splash_screen.dart
  client/lib/screen/test_screen.dart
  client/lib/secure_storage/secure_storage.dart
  client/linux/flutter/generated_plugin_registrant.cc
  client/linux/flutter/generated_plugins.cmake
  client/macos/Flutter/GeneratedPluginRegistrant.swift
  client/pubspec.lock
  client/pubspec.yaml
  client/windows/flutter/generated_plugin_registrant.cc
  client/windows/flutter/generated_plugins.cmake
Labels: Front-end

#120 Error fix
  server/accounts/views.py
Labels: bug, Back-end

#125 token api url 수정
  server/virtual_fitting_app/urls.py
Labels: bug, Back-end

#129 Frontend favorite 수정 사항 PR
  README.md
  client/lib/layout/root_tab.dart
  client/lib/screen/clotheslist_screen.dart
  client/lib/screen/favorite_screen.dart
  client/lib/screen/login_screen.dart
  client/lib/screen/signup_screen.dart
  client/lib/screen/test_detail_screen.dart
  client/macos/Flutter/GeneratedPluginRegistrant.swift
  client/pubspec.lock
  client/pubspec.yaml
  crawler/musinsa-crawler.py
  index.md
  server/accounts/__init__.py
  server/accounts/admin.py
  server/accounts/apps.py
  server/accounts/migrations/0001_initial.py
  server/accounts/migrations/__init__.py
  server/accounts/models.py
  server/accounts/tests.py
  server/accounts/urls.py
  server/accounts/views.py
  server/manage.py
  server/model_api/__init__.py
  server/model_api/admin.py
  server/model_api/apps.py
  server/model_api/migrations/__init__.py
  server/model_api/models.py
  server/model_api/tests.py
  server/model_api/views.py
  server/virtual_fitting_app/__init__.py
  server/virtual_fitting_app/asgi.py
  server/virtual_fitting_app/settings.py
  server/virtual_fitting_app/urls.py
  server/virtual_fitting_app/wsgi.py
Labels: Front-end

#138 Modify signup logic
  server/accounts/models.py
  server/accounts/serializers.py
  server/accounts/views.py
  server/s3_access/urls.py
  server/s3_access/views.py
Labels: Back-end

#142 Frontend redesign1 PR 합니다!
  client/asset/font/Pretendard-Black.ttf
  client/asset/font/Pretendard-Bold.ttf
  client/asset/font/Pretendard-ExtraBold.ttf
  client/asset/font/Pretendard-ExtraLight.ttf
  client/asset/font/Pretendard-Light.ttf
  client/asset/font/Pretendard-Medium.ttf
  client/asset/font/Pretendard-Regular.ttf
  client/asset/font/Pretendard-SemiBold.ttf
  client/asset/font/Pretendard-Thin.ttf
  client/asset/image.png
  client/asset/logo_black.png
  client/asset/logo_white.png
  client/ios/Podfile.lock
  client/lib/constant/page_url.dart
  client/lib/data/upload_image.dart
  client/lib/layout/bottom_navigator.dart
  client/lib/screen/clotheslist_screen.dart
  client/lib/screen/favorite_screen.dart
  client/lib/screen/home_screen.dart
  client/lib/screen/login_screen.dart
  client/lib/screen/signup_screen.dart
  client/lib/screen/test_detail_screen.dart
  client/macos/Flutter/GeneratedPluginRegistrant.swift
  client/pubspec.lock
  client/pubspec.yaml
Labels: Front-end

#151 [FE] 변경점들 다 수정완-
  client/asset/img/camera.jpg
  client/asset/img/gallery.jpg
  client/asset/img/loading_white.gif
  client/asset/img/musinsa.png
  client/asset/img/zzim.png
  client/lib/component/default_dialog.dart
  client/lib/constant/page_url.dart
  client/lib/data/account.dart
  client/lib/data/upload_image.dart
  client/lib/dio/dio.dart
  client/lib/main.dart
  client/lib/screen/camera_result.dart
  client/lib/screen/camera_screen.dart
  client/lib/screen/clotheslist_screen.dart
  client/lib/screen/fail_screen.dart
  client/lib/screen/favorite_screen.dart
  client/lib/screen/find_account_screen.dart
  client/lib/screen/gallery_pick_screen.dart
  client/lib/screen/home_screen.dart
  client/lib/screen/loading_screen.dart
  client/lib/screen/loading_success_screen.dart
  client/lib/screen/login_screen.dart
  client/lib/screen/my_page_screen.dart
  client/lib/screen/onboarding_screen.dart
  client/lib/screen/result_all_screen.dart
  client/lib/screen/result_screen.dart
  client/lib/screen/signup_result_screen.dart
  client/lib/screen/signup_screen.dart
  client/lib/screen/signup_success.dart
  client/lib/screen/test_detail_screen.dart
  client/lib/screen/user_info_update_screen.dart
  client/pubspec.lock
  client/pubspec.yaml
Labels: Front-end

#153 [FE] 머지에서 오류해결
  client/android/app/build.gradle
  client/flutter_launcher_icons.yaml
  client/lib/screen/camera_screen.dart
  client/lib/screen/favorite_screen.dart
  client/lib/screen/result_screen.dart
  client/web/index.html
Labels: Front-end

#155 [FE] 배포 가능하도록 수정
  client/android/app/build.gradle
  client/android/app/proguard-rules.pro
  client/android/build.gradle
  client/android/gradle/wrapper/gradle-wrapper.properties
Labels: Front-end

#167 [FE] #159 디테일 부분 수정
  client/.flutter-plugins-dependencies
  client/.idea/client.iml
  client/lib/component/async_button.dart
  client/lib/component/default_dialog.dart
  client/lib/data/user_model.dart
  client/lib/screen/camera_result.dart
  client/lib/screen/camera_screen.dart
  client/lib/screen/clotheslist_screen.dart
  client/lib/screen/favorite_screen.dart
  client/lib/screen/onboarding_screen.dart
  client/lib/screen/signup_screen.dart
  client/lib/screen/splash_screen.dart
  client/lib/screen/test_detail_screen.dart
Labels: Front-end
